import type { Metadata } from "next";

import { Providers } from "@/lib/providers";

import { ChakraProvider } from "@chakra-ui/react";

import {
  //@ts-ignore
  Container,
} from "@chakra-ui/react";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ChakraProvider>
            <Container maxW="3xl">{children}</Container>
          </ChakraProvider>
        </Providers>
      </body>
    </html>
  );
}
